# Generated by Django 2.2.5 on 2020-12-22 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nam', models.CharField(default=True, max_length=122)),
                ('email', models.EmailField(max_length=122)),
                ('phoneno', models.CharField(max_length=12)),
                ('message', models.CharField(max_length=122)),
            ],
        ),
    ]
