# Generated by Django 2.2.5 on 2020-12-24 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201222_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_slug',
            field=models.CharField(default=1, max_length=100),
        ),
        migrations.AlterField(
            model_name='register',
            name='confirmpassword',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='register',
            name='password',
            field=models.CharField(max_length=10),
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutorial_title', models.CharField(max_length=100)),
                ('tutorial_content', models.TextField()),
                ('tutorial_slug', models.CharField(default=1, max_length=120)),
                ('title', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.item')),
            ],
        ),
    ]
